import {
  Building2,
  Home,
  Landmark,
  Warehouse,
  Wifi,
  ChefHat,
  Droplet,
  SquareParking,
  Wind,
  Shirt,
  Fan,
  ThermometerSun,
  Tv,
  UtensilsCrossed,
  Bath,
} from "lucide-react-native";

export const categoryData = [
  { name: "apartment", icon: Building2 },
  { name: "house", icon: Home },
  { name: "villa", icon: Landmark },
  { name: "cabin", icon: Warehouse },
  { name: "Wifi", icon: Wifi },
  { name: "Kitchen", icon: ChefHat },
  { name: "pool", icon: Droplet },
  { name: "parking", icon: SquareParking },
  { name: "air conditioning", icon: Wind },
  { name: "washer", icon: Shirt },
  { name: "dryer", icon: Fan },
  { name: "heating", icon: ThermometerSun },
  { name: "tv", icon: Tv },
  { name: "iron", icon: UtensilsCrossed },
  { name: "hair dryer", icon: Bath },
];
