import {
  Building2,
  Home,
  Landmark,
  Warehouse,
  Wifi,
  ChefHat,
  Droplet,
  SquareParking,
  Wind,
  Shirt,
  Fan,
  ThermometerSun,
  Tv,
  UtensilsCrossed,
  Bath,
} from "lucide-react-native";

export const categoryData = [
  { name: "apartment", icon: Building2, kind: "type", value: "apartment" },
  { name: "house", icon: Home, kind: "type", value: "house" },
  { name: "villa", icon: Landmark, kind: "type", value: "villa" },
  { name: "cabin", icon: Warehouse, kind: "type", value: "cabin" },
  { name: "Wifi", icon: Wifi, kind: "amenity", value: "WiFi" },
  { name: "Kitchen", icon: ChefHat, kind: "amenity", value: "Kitchen" },
  { name: "pool", icon: Droplet, kind: "amenity", value: "Pool" },
  {
    name: "parking",
    icon: SquareParking,
    kind: "amenity",
    value: "Free parking",
  },
  {
    name: "air conditioning",
    icon: Wind,
    kind: "amenity",
    value: "Air conditioning",
  },
  { name: "washer", icon: Shirt, kind: "amenity", value: "Washer" },
  { name: "dryer", icon: Fan, kind: "amenity", value: "Dryer" },
  { name: "heating", icon: ThermometerSun, kind: "amenity", value: "Heating" },
  { name: "tv", icon: Tv, kind: "amenity", value: "TV" },
  { name: "iron", icon: UtensilsCrossed, kind: "amenity", value: "Iron" },
  { name: "hair dryer", icon: Bath, kind: "amenity", value: "Hair dryer" },
];
